<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net10.0;net10.0-android</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>LunaTV.Base</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Refit.HttpClientFactory" Version="10.1.6"/>
        <PackageReference Include="SqlSugarCore" Version="5.1.4.214"/>
        <PackageReference Include="TouchSocket.WebApi" Version="4.2.10"/>
    </ItemGroup>

</Project>
