<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <RuntimeIdentifiers>win-x64;linux-x64;osx-x64;osx-arm64</RuntimeIdentifiers>
        <Nullable>enable</Nullable>
        <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
        <!--        <PublishAot>true</PublishAot>-->
        <Version>0.9.5</Version>
        <AssemblyVersion>0.9.5.4</AssemblyVersion>
        <ApplicationIcon>Assets/logo-tv.ico</ApplicationIcon>
    </PropertyGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\**"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="AsyncImageLoader.Avalonia" Version="3.8.0"/>
        <PackageReference Include="Avalonia" Version="12.0.3"/>
        <PackageReference Include="Avalonia.Desktop" Version="12.0.3"/>
        <!--Condition below is needed to remove AvaloniaUI.DiagnosticsSupport package from build output in Release configuration.-->
        <PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.1">
            <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
            <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Avalonia.Labs.Gif" Version="12.0.2"/>
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2"/>
        <PackageReference Include="DataChannelDotnet" Version="1.3.1"/>
        <PackageReference Include="Irihi.Ursa" Version="2.0.0"/>
        <PackageReference Include="Irihi.Ursa.Themes.Semi" Version="2.0.0"/>
        <PackageReference Include="Material.Icons.Avalonia" Version="3.0.2"/>
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.8"/>
        <PackageReference Include="Microsoft.Extensions.Http.Resilience" Version="10.6.0"/>
        <PackageReference Include="Semi.Avalonia" Version="12.0.1"/>
        <PackageReference Include="Semi.Avalonia.DataGrid" Version="12.0.0"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\LibMPV\LibMpv.Avalonia\LibMpv.Avalonia.csproj"/>
        <ProjectReference Include="..\LunaTV.Base\LunaTV.Base.csproj"/>
        <ProjectReference Include="..\M3U8Download\M3U8Download.csproj"/>
    </ItemGroup>

    <ItemGroup Condition="'$(RuntimeIdentifier)'=='win-x64' or '$(RuntimeIdentifier)'==''">
        <Content Include="ffmpeg\win-x64\**">
            <Link>%(Filename)%(Extension)</Link>
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
    </ItemGroup>

    <Target Condition="'$(RuntimeIdentifier)'=='win-x64' or '$(RuntimeIdentifier)'==''" Name="ExtractZipFiles" AfterTargets="Build">
        <Exec Command="powershell -Command &quot;Expand-Archive -Path '$(OutputPath)libmpv-2.zip' -DestinationPath '$(OutputPath)' -Force; Remove-Item -Path '$(OutputPath)libmpv-2.zip' -Force&quot;" ContinueOnError="true"/>
    </Target>
</Project>